### PR TITLE
Fix wasm non-web usage of env::now

### LINKED ISSUE #118: Upgrading from 0.14.0 to 0.14.1 breaks compatibility with `wasm32-unknown-unknown` target
puffin 0.14.1 introduces a new required wasm import `env::now`, that's apparently imported by `instant`. I suspect this is coming from the js-sys ecosystem, or it might even be a WASI standard. There should be a way to opt out of this, so one can use `puffin` in `wasm32-unknown-unknown` environments too.

It seems that 0.14.0 didn't depend at all on `instant`, so making the dependency on `instant` optional + reuse whatever was used before to retrieve the time, should be sufficient to fix this.

### PR DESCRIPTION
**Pull request by bnjbvr**
### Checklist

* [x] I have read the [Contributor Guide](../CONTRIBUTING.md)
* [x] I have read and agree to the [Code of Conduct](../CODE_OF_CONDUCT.md)
* [x] I have added a description of my changes and why I'd like them included in the section below

### Description of Changes

A wasm embedder that hasn't enabled the `web` feature will still get the `Instant::now()` function generated, even if they end up using a custom `now` function. After all, the compiler/link don't have runtime knowledge about how the program runs, so it could be that `ThreadProfiler::initialize` is never called, so the default value of `now_ns` that makes use of `Instant::now` could be called at any point.
 
This changes the `now_ns` function so it's defined only using `Instant` for native target and wasm when web is enabled. In the other case, we assume this is never called and it's a programmer error because we don't have any time reporter. I didn't want to cause a `panic!` in there, so returned a dummy value instead; let me know what you think is preferred.

### Related Issues

Fixes #118.

### CODE REVIEW

File: puffin/src/lib.rs [hunk 1]
```diff
@@ -566,6 +560,13 @@ pub fn now_ns() -> NanoSecond {
     START_TIME.0 + START_TIME.1.elapsed().as_nanos() as NanoSecond
 }
 
+#[inline]
+#[cfg(all(target_arch = "wasm32", not(feature = "web")))]
+pub fn now_ns() -> NanoSecond {
+    // This should be unused.
+    0
```
Comment (emilk) [inline puffin/src/lib.rs:567]: I personally prefer loud error (panic) to "why the hell doesn't my profiler work!?!?!"

Comment (bnjbvr) [reply puffin/src/lib.rs]: Makes sense too, yeah. I've done that now.

**Review by TimonPost — APPROVED** [review]
